In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# Ignore all warnings
warnings.filterwarnings("ignore")

In [2]:
df_test=pd.read_excel("/content/test.xlsx")

In [3]:
df_test.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Male,0,No,No,25,Yes,No,Fiber optic,Yes,no,yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,106.00,2787.00
1,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,30.00,30.00
2,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
3,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
4,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85

In [4]:
df_test.shape

(20, 19)

In [5]:
df_test.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [6]:
df_test.describe()

       SeniorCitizen     tenure  MonthlyCharges  TotalCharges
count           20.0  20.000000       20.000000     20.000000
mean             0.0  21.400000       65.662500   1680.355000
std              0.0  19.701456       32.801412   1737.730413
min              0.0   1.000000       18.950000     29.850000
25%              0.0   2.000000       29.962500    140.775000
50%              0.0  19.000000       56.550000   1330.625000
75%              0.0  29.500000      101.187500   2787.000000
max              0.0  62.000000      106.000000   5681.100000

In [7]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            20 non-null     object
 1   SeniorCitizen     20 non-null     int64
 2   Partner           20 non-null     object
 3   Dependents        20 non-null     object
 4   tenure            20 non-null     int64
 5   PhoneService      20 non-null     object
 6   MultipleLines     20 non-null     object
 7   InternetService   20 non-null     object
 8   OnlineSecurity    20 non-null     object
 9   OnlineBackup      20 non-null     object
 10  DeviceProtection  20 non-null     object
 11  TechSupport       20 non-null     object
 12  StreamingTV       20 non-null     object
 13  StreamingMovies   20 non-null     object
 14  Contract          20 non-null     object
 15  PaperlessBilling  20 non-null     object
 16  PaymentMethod     20 non-null     object
 17  MonthlyCharges    20 non-null     float64
 18  TotalCharges      20 non-null     float64
dtypes: float64(2), int64(2), object(15)
memory usage: 3.1+ KB

In [8]:
# print numerical columns
num_cols = df_test.select_dtypes(include=['float64', 'int64']).columns
print("Numerical columns:", num_cols)

# print categorical columns
cat_cols = df_test.select_dtypes(include=['object']).columns
print("Categorical columns:", cat_cols)

Numerical columns: Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='object')
Categorical columns: Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='object')

In [9]:
df_test.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
dtype: int64

In [10]:
df_test.dropna(inplace=True)

In [11]:
df_test.TotalCharges = pd.to_numeric(df_test.TotalCharges, errors='coerce')

In [12]:
df_test.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder

# create a LabelEncoder object
le = LabelEncoder()

# apply label encoding to each categorical column in the dataframe
for col in cat_cols:
    df_test[col] = le.fit_transform(df_test[col])

In [14]:
from sklearn.preprocessing import StandardScaler

# create a StandardScaler object
scaler = StandardScaler()

# fit the scaler to the training data and transform it
X_test_scaled = scaler.fit_transform( df_test)

In [15]:
df_test.to_excel('test1.xlsx', index=False)